global:
  scrape_interval:     10s
  evaluation_interval: 1s

rule_files:
  - "targets.rules"


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'test'
    static_configs:
      - targets: ['IP:9100']
        labels:
          instance: test

